apiVersion: v1
kind: Service
metadata:
  name: trader-tools
  namespace: trader-tools
  labels:
    app: trader-tools
spec:
  type: ClusterIP
  selector:
    app: trader-tools
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours for session persistence
